/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PingerIndexRouteImport } from './routes/pinger/index'
import { Route as PingIndexRouteImport } from './routes/ping/index'
import { Route as FriendsIndexRouteImport } from './routes/friends/index'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PingerIndexRoute = PingerIndexRouteImport.update({
  id: '/pinger/',
  path: '/pinger/',
  getParentRoute: () => rootRouteImport,
} as any)
const PingIndexRoute = PingIndexRouteImport.update({
  id: '/ping/',
  path: '/ping/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/friends': typeof FriendsIndexRoute
  '/ping': typeof PingIndexRoute
  '/pinger': typeof PingerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/friends': typeof FriendsIndexRoute
  '/ping': typeof PingIndexRoute
  '/pinger': typeof PingerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/friends/': typeof FriendsIndexRoute
  '/ping/': typeof PingIndexRoute
  '/pinger/': typeof PingerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$path'
    | '/friends'
    | '/ping'
    | '/pinger'
    | '/api/auth/$'
    | '/api/push/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$path'
    | '/friends'
    | '/ping'
    | '/pinger'
    | '/api/auth/$'
    | '/api/push/subscribe'
  id:
    | '__root__'
    | '/'
    | '/auth/$path'
    | '/friends/'
    | '/ping/'
    | '/pinger/'
    | '/api/auth/$'
    | '/api/push/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthPathRoute: typeof AuthPathRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
  PingIndexRoute: typeof PingIndexRoute
  PingerIndexRoute: typeof PingerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinger/': {
      id: '/pinger/'
      path: '/pinger'
      fullPath: '/pinger'
      preLoaderRoute: typeof PingerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping/': {
      id: '/ping/'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthPathRoute: AuthPathRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  PingIndexRoute: PingIndexRoute,
  PingerIndexRoute: PingerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
